config/routes.rb
class ActionDispatch::Routing::Mapper
    def draw(routes_name)
        instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
    end
end

Rails.application.routes.draw do

  resources :contacts
	scope module: 'api' do
        draw :apiv1
    end

    match '/' => 'homes#index', :via => [:get, :post]
    match 'confirm_account' => "homes#confirm_account", :via => [:get]
    match 'admin' => 'dashboard#index', :via => [:get]

    get "/grid/*path" => "gridfs#serve"

    resources :products
    match '/product_comments/:id' => "products#comments", :via => [:get, :post]
    match '/product_bids/:id' => "products#bids", :via => [:get, :post]

    resources :users, :only => [:show, :index]
    match '/user_bids/:id' => "users#bids", :via => [:get, :post]
    match '/user_products/:id' => "users#products", :via => [:get, :post]

    get "/subscribe_to_chat/:product_id/:user_id" => "chats#subscribe_to_chat", :via => [:get, :post], :defaults => { :format => 'json' }
    match "/unsubscribe_to_chat" => "chats#unsubscribe_to_chat", :via => [:get, :post], :defaults => { :format => 'json' }
    match "/add_chat_message" => "chats#add_chat_message", :via => [:get, :post], :defaults => { :format => 'json' }
    match 'contact' => "homes#contact", :via => [:post]
    resources :cities
    resources :states
    resources :countries
    resources :categories
    resources :qualities
    resources :brands
    resources :contacts

    devise_for :admins, :controllers => {:registrations => "registrations"}
    # match '*path', to: redirect('admin'), via: :all
    root 'homes#index'
end

app/views/layouts/app/_header.html.erb
<header class="main-header">
    <a href="<%= admin_path %>" class="logo">
        <span class="logo-mini"><img src="<%= asset_path('logo.png')%>" width="30px"></span>
        <span class="logo-lg"><b>Shapp</b></span>
    </a>
    <nav class="navbar navbar-static-top">
        <a href="javascript:void(0)" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown messages-menu">
                    <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-envelope-o"></i>
                        <span class="label label-success">4</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 4 messages</li>
                        <li>
                            <ul class="menu">
                                <li>
                                    <a href="javascript:void(0)">
                                        <div class="pull-left">
                                            <img src="<%= asset_path('user2-160x160.jpg')%>" class="img-circle" alt="User Image">
                                        </div>
                                        <h4>
                                            Support Team
                                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer"><a href="javascript:void(0)">See All Messages</a></li>
                    </ul>
                </li>

                <li class="dropdown notifications-menu">
                    <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                        <span class="label label-warning">10</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 10 notifications</li>
                        <li>
                            <ul class="menu">
                                <li>
                                    <a href="javascript:void(0)">
                                        <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer"><a href="javascript:void(0)">View all</a></li>
                    </ul>
                </li>

                <li class="dropdown tasks-menu">
                    <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-flag-o"></i>
                        <span class="label label-danger">9</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 9 tasks</li>
                        <li>
                            <ul class="menu">
                                <li>
                                    <a href="javascript:void(0)">
                                        <h3>
                                            Design some buttons
                                            <small class="pull-right">20%</small>
                                        </h3>
                                        <div class="progress xs">
                                            <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                <span class="sr-only">20% Complete</span>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer">
                            <a href="javascript:void(0)">View all tasks</a>
                        </li>
                    </ul>
                </li>

                <li class="dropdown user user-menu">
                    <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="<%= asset_path('user2-160x160.jpg')%>" class="user-image" alt="User Image">
                        <span class="hidden-xs"><%= "#{current_admin.first_name} #{current_admin.last_name}" %></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-header">
                            <img src="<%= asset_path('user2-160x160.jpg')%>" class="img-circle" alt="User Image">
                            <p>
                                <%= "#{current_admin.first_name} #{current_admin.last_name}" %>
                            </p>
                        </li>
                        <li class="user-footer">
                            <div class="pull-left">
                                <%= link_to "Profile", edit_admin_registration_path, :class => 'btn btn-default btn-flat' %>
                            </div>
                            <div class="pull-right">
                                <%= link_to 'Sign out', destroy_admin_session_path, :method => :delete, :class => 'btn btn-default btn-flat' %>
                            </div>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="javascript:void(0)" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

app/views/layouts/app/_sidebar.html.erb
<aside class="main-sidebar">
    <section class="sidebar">
        <ul class="sidebar-menu">
            <li>
                <a href="<%= admin_path %>">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>
            </li>
            <li>
                <a href="<%= users_path %>">
                    <i class="fa fa-users"></i> <span>Users</span>
                </a>
            </li>
            <li>
                <a href="<%= products_path %>">
                    <i class="fa fa-file-text"></i> <span>Products</span>
                </a>
            </li>
            <li>
                <a href="<%= categories_path %>">
                    <i class="fa fa-tags"></i> <span>Categories</span>
                </a>
            </li>
            <li>
                <a href="<%= contacts_path %>">
                    <i class="fa fa-tags"></i> <span>Contacts</span>
                </a>
            </li>
            <li>
                <a href="<%= brands_path %>">
                    <i class="fa fa-info-circle" aria-hidden="true"></i> <span>Brands</span>
                </a>
            </li>
            <li class="treeview">
                <a href="javascript:void(0)">
                    <i class="fa fa-location-arrow"></i>
                    <span>Locations</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li>
                        <a href="<%= countries_path %>"><i class="fa fa-circle-o"></i> Countries</a>
                        <a href="<%= states_path %>"><i class="fa fa-circle-o"></i> States</a>
                        <a href="<%= cities_path %>"><i class="fa fa-circle-o"></i> Cities</a>
                    </li>
                </ul>
            </li>
        </ul>
    </section>
</aside>

app/views/layouts/app/_sub_header.html.erb
<% unless @head_title.blank? %>
    <section class="content-header">
        <h1>
            <%= @head_title %>
        </h1>
    </section>
<% end %>