config/routes.rb
class ActionDispatch::Routing::Mapper
    def draw(routes_name)
        instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
    end
end

Rails.application.routes.draw do

  resources :contacts
	scope module: 'api' do
        draw :apiv1
    end

    match '/' => 'homes#index', :via => [:get, :post]
    match 'confirm_account' => "homes#confirm_account", :via => [:get]
    match 'admin' => 'dashboard#index', :via => [:get]

    get "/grid/*path" => "gridfs#serve"

    resources :products
    match '/product_comments/:id' => "products#comments", :via => [:get, :post]
    match '/product_bids/:id' => "products#bids", :via => [:get, :post]

    resources :users, :only => [:show, :index]
    match '/user_bids/:id' => "users#bids", :via => [:get, :post]
    match '/user_products/:id' => "users#products", :via => [:get, :post]

    get "/subscribe_to_chat/:product_id/:user_id" => "chats#subscribe_to_chat", :via => [:get, :post], :defaults => { :format => 'json' }
    match "/unsubscribe_to_chat" => "chats#unsubscribe_to_chat", :via => [:get, :post], :defaults => { :format => 'json' }
    match "/add_chat_message" => "chats#add_chat_message", :via => [:get, :post], :defaults => { :format => 'json' }
    match 'contact' => "homes#contact", :via => [:post]
    resources :cities
    resources :states
    resources :countries
    resources :categories
    resources :qualities
    resources :brands
    resources :contacts

    devise_for :admins, :controllers => {:registrations => "registrations"}
    # match '*path', to: redirect('admin'), via: :all
    root 'homes#index'
end

app/models/brand.rb
class Brand
  	include Common

  	field :name, type: String
  	belongs_to :category, :class_name => "Category", :index => true, :inverse_of => :category

  	has_many :item_models
  	accepts_nested_attributes_for :item_models, :reject_if => :all_blank, :allow_destroy => true

  	def self.search(search)
        if search
            any_of({:name => /#{search}/i})
        end
    end

    def to_api
    	return {:id => self.id.to_s, :name => self.name, :has_models => self.item_models.count}
    end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
    include App

    before_action :set_brand, only: [:show, :edit, :update, :destroy]

    def index
        respond_to do |format|
            format.html
            format.json { render json: BrandsDatatable.new(view_context) }
        end
    end

    def show
    end

    def new
        @brand = Brand.new
    end

    def edit
    end

    def create
        @brand = Brand.new(brand_params)
        respond_to do |format|
            if @brand.save
                format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
                format.json { render :show, status: :created, location: @brand }
            else
                format.html { render :new }
                format.json { render json: @brand.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
            if @brand.update(brand_params)
                format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
                format.json { render :show, status: :ok, location: @brand }
            else
                format.html { render :edit }
                format.json { render json: @brand.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @brand.destroy
        respond_to do |format|
            format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    def set_brand
        @brand = Brand.find(params[:id])
    end

    def brand_params
        params.require(:brand).permit(:category_id, :name, item_models_attributes: [:id, :name, :is_enabled, :_destroy])
    end
end

app/views/brands/_form.html.erb
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Brands</h3>
        <div class="box-tools pull-right">
          <%= link_to 'Cancel', brands_path, :class => 'btn btn-default btn-sm'%>
        </div>
    </div>
</div>
<div class="row">
        <%= nested_form_for @brand, :html => {:class => 'form-horizontal'} do |f| %>
            <div class="col-sm-6">
                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title"><%= params[:action] == 'edit' ? "Edit Brand" : 'New Brand'%></h3>
                    </div>
                    <div class="box-body">
                        <% if @brand.errors.any? %>
                            <%= render :partial => "layouts/errors", :locals => {:errors => @brand.errors} %>
                        <% end %>
                        <div class="form-group">
                            <label for="state[name]" class="col-sm-2 control-label">Category</label>
                            <div class="col-sm-10">
                                <%= f.select :category_id, Category.all.collect {|p| [ p.name, p.id ]} , {},:class => 'form-control' %>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="state[country]" class="col-sm-2 control-label">Name</label>
                            <div class="col-sm-10">
                              <%= f.text_field :name, :class => 'form-control', :placeholder => 'Brand Name' %>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-info pull-left">Submit</button>&nbsp;&nbsp;&nbsp;
                        <%= link_to "Cancel", brands_path, :class => "btn btn-default"%>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title"><%= params[:action] == 'edit' ? "Edit Models" : 'Add Models'%></h3>
                    </div>
                    <div class="box-body">
                        <table id="models" class="table table-bordered">
                            <tr>
                                <th>Name</th>
                                <th>Enabled</th>
                                <th>Action</th>
                            </tr>
                            <%= f.fields_for :item_models, :wrapper => false do |task_form| %>
                                <tr class="fields">
                                    <td>
                                        <%= task_form.text_field :name, :class => 'form-control', :placeholder => "Model Name" %>
                                    </td>
                                    <td>
                                        <div class="checkbox">
                                            <label>
                                                <%= task_form.check_box :is_enabled %>
                                            </label>
                                        </div>
                                    </td>
                                    <td>
                                        <%= task_form.link_to_remove "<i class='fa fa-trash'></i>".html_safe %>
                                    </td>
                                </tr>
                            <% end %>
                        </table>
                        <br />
                        <%= f.link_to_add "Add Model", :item_models, :data => { :target => "#models" }, :class => 'btn btn-sm btn-block btn-success' %>
                    </div>
                </div>
            </div>
    <% end %>
</div>

app/views/brands/edit.html.erb
<%= render 'form' %>

app/views/brands/index.html.erb
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Brands</h3>
        <div class="box-tools pull-right">
            <div class="has-feedback">
                <%= link_to '<i class="fa fa-plus"></i> &nbsp;Add Brand'.html_safe, new_brand_path, :class => 'btn btn-block btn-info btn-sm'%>
            </div>
        </div>
    </div>
    <div class="box-body">
        <table id="brands_table" class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th class="sorting_disabled center" style="width: 31px !important"></th>
                    <th>Name</th>
                    <th class="sorting_disabled">Category</th>
                    <th class="sorting_disabled">Created At</th>
                    <th class="sorting_disabled">Action</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="dataTables_empty" colspan="5">Loading brands from server</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<script>
  $(document).ready(function(){
    $("#brands_table").dataTable({
        "bJQueryUI"       : true,
        "bProcessing"     : true,
        "bAutoWidth"      : false,
        "sPaginationType" : "full_numbers",
        "aoColumns"       : [{"sType" : "html"}, null, null, null, null],
        "aaSorting"       : [[0, 'asc'], [1, 'asc']],
        "bServerSide"     : true,
        "sAjaxSource"     : "/brands.json",
        "language": {
            "zeroRecords": "No brands found",
            "infoEmpty": "No brands available"
        }
    })
  })
</script>

app/views/brands/new.html.erb
<%= render 'form' %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @brand.category %>
</p>

<p>
  <strong>Name:</strong>
  <%= @brand.name %>
</p>

<% for item_model in @brand.item_models %>
	<%= item_model.name %> <br />
<% end %>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>